version: "3"
services:
  web:
    image: atsushikoga/apache-php:2.4-7.2
    ports:
      - "80:80"
    privileged: true
    links:
      - db
    volumes:
      - "./:/var/www/html"
    container_name: "apache-php"
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    container_name: "psql"
